spring.application.name=ecomerceappapi

server.servlet.context-path=/api/v1/
jwt_secret= "birajroythisisaverysecuresecretkeyforjwt123456";
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=Biraj0000@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
cloudinary.api_key=618363189349156
cloudinary.api_secret=HHnsd2n8Qx5wpaxWoNQth5leTGI
cloudinary.cloud_name=dwqibzr7g
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect